CREATE DATABASE IF NOT EXISTS `ardentguard-api`;

USE `ardentguard-api`;

CREATE TABLE IF NOT EXISTS `clients` (
  `ClientID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ClientName` VARCHAR(255) NOT NULL,
  `DomainNames` TEXT NOT NULL, /* JSON for domains, DNS TXT records, and verification status */
  `LoginEmail` VARCHAR(255) NOT NULL UNIQUE,
  `Password` VARCHAR(255) NOT NULL,
  `ContactPersonName` VARCHAR(255) NOT NULL,
  `ContactEmail` VARCHAR(255) NOT NULL,
  `BillingEmail` VARCHAR(255) NOT NULL,
  `Active` BOOLEAN NOT NULL DEFAULT TRUE,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `jobs` (
  `JobID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ClientID` BIGINT UNSIGNED NOT NULL,
  `Status` TINYINT UNSIGNED NOT NULL CHECK (`Status` BETWEEN 0 AND 10),
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`ClientID`) REFERENCES `clients` (`ClientID`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `results` (
  `ResultID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ClientID` BIGINT UNSIGNED NOT NULL,
  `JobID` BIGINT UNSIGNED NOT NULL,
  `Output` LONGTEXT NOT NULL,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`ClientID`) REFERENCES `clients` (`ClientID`) ON DELETE CASCADE,
  FOREIGN KEY (`JobID`) REFERENCES `jobs` (`JobID`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `reports` (
  `reportID` INT AUTO_INCREMENT PRIMARY KEY,
  `ClientID` BIGINT UNSIGNED NOT NULL,
  `Status` TINYINT NOT NULL,
  `S3URL` TEXT,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`ClientID`) REFERENCES `clients` (`ClientID`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `batch_jobs` (
  `BatchID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ClientID` BIGINT UNSIGNED NOT NULL,
  `JobIDs` JSON NOT NULL, /* Holds a JSON list of JobIDs */
  `Status` TINYINT UNSIGNED NOT NULL CHECK (`Status` BETWEEN 0 AND 10),
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`ClientID`) REFERENCES `clients` (`ClientID`) ON DELETE CASCADE
) ENGINE=InnoDB;

