version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: ardentguard_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./certs:/certs  # Mount SSL certificates
      - ./config:/etc/mysql/conf.d  # Custom configuration for SSL
    ports:
      - "0.0.0.0:3306:3306"  # Bind to all interfaces
    command:
      - "--bind-address=0.0.0.0"

volumes:
  db_data:

