version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: ardentguard_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./config/ssl.cnf:/etc/mysql/conf.d/ssl.cnf
      - ./letsencrypt:/etc/mysql/ssl:ro
    ports:
      - "3306:3306"
    command:
      - "--bind-address=0.0.0.0"
      - "--require_secure_transport=ON"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    entrypoint: sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'

volumes:
  db_data:
  letsencrypt:

